baseURL = "https://aotsuki.blog/"
languageCode = "ja"
title = "Aotsuki's blog"
theme = "PaperMod"
copyright = "© 2026 Aotsuki"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowPageNums = true
ShowAllPagesInArchive = true
ShowRssButtonInSectionTermList = true
ShowShareButtons = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  author = "Aotsuki"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true
  math = true

  mainSections = ["math", "cp", "diary"]  # 全体の最新一覧にしたいなら

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Cyanmond"

  [[params.socialIcons]]
    name = "X"
    url = "https://x.com/account_name"

  [params.homeInfoParams]
    Title = "Aotsuki's blog"
    Content = """
イギリスで数学科受験生。
数学とか競技プログラミングとか、日記とかを書きます。
"""
  [params.label]
    text = "Aotsuki's blog"

  [params.assets]
    favicon = "/favicon.png"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]